### ISSUE TITLE
On screen/console/stderr output.

### ISSUE THREAD

**Issue by TomODwyer-SES** [Open-SES/OpenSES#5]
The program, in its current form, provides no real-time display of simulation progress to the console.  Having the ability to toggle the feature on/off from the is required for unattended/batch processing.  

-Tom

**Comment by NeverGray** [comment]
Hi Tom, 
How hard is it to add a toggle for the 4.2 release? If the toggle is difficult, I recommend the first default behavior reports progress to the console. Later, the toggle can be added in 4.3 to disable default behavior.

**Reasoning:** I think the program should as easy to use for novice users. Having a status output helps novices know the program started. Otherwise, they are staring at a blank screen thinking, "did I do something wrong?"

Advanced users who do lots of batch processing are more accepting of adding toggles to change the default behavior. 

Justin

**Comment by TomODwyer-SES** [comment]
It is not difficult to add the toggle, just takes some time.
-Tom

**Comment by NeverGray** [comment]
What do you want for the default behavior of 4.2?
1) Keep as-is with not status
2) Spend time and add status to the output screen (similar to SES 6.0). A toggle will be added to 4.3
3) Add toggle to 4.2.

**Comment by TomODwyer-SES** [comment]
To move things along, I did not add toggle for screen output.  
-Tom
